name: node_exporter
image: prom/node-exporter:latest

args:
- --path.procfs=/host/proc
- --path.rootfs=/rootfs
- --path.sysfs=/host/sys
- --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
- --collector.textfile.directory=/var/lib/node_exporter/textfile_collector

mounts:
- source: /proc
  target: /host/proc
  read_only: true
- source: /sys
  target: /host/sys
  read_only: true
- source: /
  target: /rootfs
  read_only: true
- source: /var/lib
  target: /var/lib
  read_only: false
- source: /var/log
  target: /var/log
  read_only: false
- source: /etc/timezone
  target: /etc/timezone
  read_only: true
- source: /etc/localtime
  target: /etc/localtime
  read_only: true

timezone:
  bind_local: true
  env_tz: true

networks:
- monitor-net

ports:
- published: 9100
  target: 9100
  protocol: tcp
  mode: host

deploy:
  mode: global
  endpoint_mode: vip
  placement:
    constraints:
    - node.platform.os == linux
  labels:
    compose.version: "full"
    swarm.stack: "swarm-dev"
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 2
    window: 60s

labels:
  org.label-schema.group: monitoring
  swag: enable
  swag.uptime-kuma.enabled: true
  swag.uptime-kuma.monitor.name: Node-Exporter
  swag.uptime-kuma.monitor.url: https://node-exporter.${TLD}

stop_grace_period: 30s
stop_signal: SIGTERM

healthcheck:
  test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:9100/metrics || exit 1" ]
  interval: 30s
  timeout: 10s
  retries: 5
  start_period: 20s

logging:
  driver: json-file
  options:
    max-size: 10m
    max-file: 5
