comonitor_interval_seconds: 30

default:
  cooldown_minutes: 15
  sustained_high_minutes: 10
  memory_difference_gb: 2

# Node exporter runs on Proxmox host to report memory for the corresponding VM
node_exporter_nodes:
  hl-core-proxmox:
    exporter_url: http://192.168.69.118:9100/metrics

# Map Docker VM nodes → physical Proxmox host node_exporter
node_map:
  hl-core-ubuntu: hl-core-proxmox
  hl-node02-ubuntu: hl-node02-proxmox
  hl-node03-ubuntu: hl-node03-proxmox

services:
  semaphore_db:
    cooldown_minutes: 30
    memory_difference_gb: 3
  gitea_db: {}
  komodo_db: {}
