# swarm.yml
#
# Purpose:
#   Centralizes all static node information and service dependency rules for Orcastra.
#   Defines:
#     - Node membership (IPs, labels, leader node)
#     - Static node labels for Swarm scheduling
#     - Anchor services and their dependent services (for co-location)
#
# Structure:
#   - leader: The hostname of the Swarm leader node.
#   - advertise_addr: The IP address used by Swarm to advertise itself.
#   - nodes: Static inventory of Swarm nodes with IPs and labels.
#   - options: Global behavior settings (e.g., whether to prune unknown labels).
#   - dependencies: Anchor services and their dependent services.
#
# Notes:
#   - Node labels are enforced during bootstrap and static label synchronization.
#   - Anchor services (like databases) ensure dependent services always run on the same node.
#   - retry_intervals define cooldowns before trying to restart a failed or misplaced service.
#   - Swarm stack name is prepended automatically during runtime (e.g., swarm-dev_semaphore).

# | Constraint Key         | Description                                                                 |
# |------------------------|-----------------------------------------------------------------------------|
# | `node.hostname`        | Matches the Docker hostname (e.g., `node.hostname == hl-core-ubuntu`)       |
# | `node.id`              | Matches the internal Swarm node ID                                          |
# | `node.role`            | `manager` or `worker`                                                       |
# | `node.platform.os`     | Operating system (usually `linux`)                                          |
# | `node.platform.arch`   | Architecture (e.g., `amd64`, `arm64`)                                       |
# | `node.platform.variant`| Variant (e.g., `v7`, `v8` on ARM systems) — usually empty on x86            |
# | `engine.labels.*`      | Matches Docker Engine labels (like `engine.labels.storage=ssd`)             |
# | `engine.version`       | Docker Engine version (e.g., `engine.version == 24.0.6`)                    |

leader: hl-core-ubuntu
advertise_addr: 192.168.69.119

nodes:
  hl-node03-proxmox:
    ip: 192.168.69.116
    labels: [ hl-node-03-proxmox, homelab, proxmox, zfs, tdarr ]
  hl-node02-proxmox:
    ip: 192.168.69.117
    labels: [ hl-node02-proxmox, testing, homelab, proxmox, zfs, tdarr ]
  hl-core-proxmox:
    ip: 192.168.69.118
    labels: [ hl-core-proxmox, homelab, proxmox, zfs, tdarr ]
  hl-core-ubuntu:
    ip: 192.168.69.119
    labels: [ hl-core-ubuntu, testing, homelab, ubuntu, ext4 ]
  hl-node02-ubuntu:
    ip: 192.168.69.120
    labels: [ hl-node02-ubuntu, homelab, ubuntu, ext4 ]
  hl-node03-ubuntu:
    ip: 192.168.69.121
    labels: [ hl-node03-ubuntu, testing, homelab, ubuntu, ext4 ]
  rworkstation:
    ip: 192.168.69.150
    labels: [ rworkstation, tdarr-wide ]
  rthinkpad:
    ip: 192.168.69.151
    labels: [ rthinkpad, tdarr-wide ]

options:
  prune_unknown_labels: false

# co-location dependencies
dependencies:

  ## SWARM-AI

  ollama:
    stack: swarm-ai
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - anythingllm

  ## SWARM-CLOUD

  bitwarden_db:
    stack: swarm-cloud
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - bitwarden

  nextcloud_db:
    stack: swarm-cloud
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - nextcloud
    - nextcloud_redis
    - documentserver

  linkwarden_db:
    stack: swarm-cloud
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - linkwarden
    - linkwarden_meili

  paperless_db:
    stack: swarm-cloud
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - paperless-ngx
    - paperless_redis

  ## SWARM-CONTENT

  recipes_db:
    stack: swarm-content
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - recipes

  nitter:
    stack: swarm-content
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - nitter_redis

  proxitok:
    stack: swarm-content
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - proxitok_redis
    - proxitok_chromedriver

  libremdb:
    stack: swarm-content
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - libremdb_redis

  quetre:
    stack: swarm-content
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - quetre_redis

  joplin_db:
    stack: swarm-content
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - joplin

  ## SWARM-DEV

  semaphore_db:
    stack: swarm-dev
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - semaphore

  gitea_db:
    stack: swarm-dev
    restart_dependents: false
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - gitea
    - gitea_redis

  komodo_db:
    stack: swarm-dev
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - komodo_core
    - komodo_periphery

  couchdb:
    stack: swarm-dev
    restart_dependents: false
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - influxdbv1
    - swarmpit

  guacamole_db:
    stack: swarm-dev
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - guacd
    - guacamole

  ## SWARM-LIBRARY

  tubearchivest:
    stack: swarm-library
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - archivist_redis
    - archivist_es

  ## SWARM-PROXY

  # crowdsec_db:
  #   stack: swarm-proxy
  #   restart_dependents: true
  #   retry_intervals: [ 2, 10, 60, 300, 900 ]
  #   services:
  #   - crowdsec
  #   - crowdsec-cf-bouncer

  authentik_db:
    stack: swarm-proxy
    restart_dependents: true
    retry_intervals: [ 2, 10, 60, 300, 900 ]
    services:
    - authentik_redis
    - authentik-server
    - authentik-worker
