name: Build and Push

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag"
        required: true
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag ghcr.io/princinv/orcastra:${{ github.event.inputs.version }} \
            --push \
            --provenance=false \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --compress .
